read arrays and store them in output message
rlindner/node-red-contrib-sma-webconnect pull request #13
Opened 2020-10-31 15:26 UTC by HoLo85

Added capability to store message arrays in custom messages.

2020-11-13 21:41 UTC, rlindner requested changes
First of all, thanks again for your contribution and sorry again for the delay :bow:

I wasn't really able to test this properly, but from my understanding the values in question are of the following format?

```json
"6100_40263F00": {
  "7": [
    {
      "val": 123
    },
    {
      "val": 456
    }
  ]
}
```

If that's the case, everything should be OK. Just one nit pick: Please let's just use an array and get rid of that counter.

2020-11-13 21:41 UTC, rlindner commented on sma-webconnect.js
> +                    var val_arr = []; // value array
```suggestion
                    var values = [];
```

2020-11-13 21:41 UTC, rlindner commented on sma-webconnect.js
> +                        val_arr[val_cnt++] = tmp;
```suggestion
                        values.push(tmp);
```

2020-11-13 21:41 UTC, rlindner commented on sma-webconnect.js
> +                      result[message.values[key].name] = val_arr[0];
```suggestion
                    if (values.length > 1) {
                      result[message.values[key].name] = values;
                    } else {
                      result[message.values[key].name] = values[0];
```

2020-11-15 10:13 UTC, HoLo85 commented
hi, updated the PR.
The returned array values look like this with the current implementation:
`{"dc_power":[2067,479],"dc_voltage":[58645,40779],"dc_current":[3527,1178],"available_sessions":2}`

2020-11-15 14:56 UTC, HoLo85 commented
Had to do an update to the code so messages with objects get stored if requested. The current output will stay the same as now but extended by the object message.

Input:
`{
    "sma_config": {
        "id": "1",
        "values": {
            "6100_0046E500": {
                "name": "phase1_voltage",
                "divider": 1
            },
            "6380_40251E00": {
                "name": "dc_power",
                "divider": 1
            },
            "6380_40451F00": {
                "name": "dc_voltage",
                "divider": 1
            },
            "6380_40452100": {
                "name": "dc_current",
                "divider": 1
            },
            "6180_00522900": {
                "name": "unknown",
                "divider": 1
            },
            "6180_08652500": {
                "name": "unknown2",
                "divider": 1
            }
        }
    }
}`
Output:
`{
    "phase1_voltage":23543,
    "dc_power":[156,404],
    "dc_voltage":[56146,33022],
    "dc_current":[279,1226],
    "unknown":{
        "low":0,
        "high":0,
        "val":null
    },
    "unknown2":{
        "tag":303
    },
    "available_sessions":1
}`

2020-11-16 21:11 UTC, merged